cliente/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from cliente.views import *

app_name='cliente'

urlpatterns = [
    path('registrar_usuario/', registrar_usuario, name='registrar_usuario'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('editar_datos/', editar_datos, name="editar_datos"),
    path('cambiar_contrasena/', cambiar_contrasena, name="cambiar_contrasena"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpsfood/urls.py
from django.contrib import admin
from django.urls import path, include
from receta.views import *
from gestion_usuarios.views import *
from django.conf import settings
from django.conf.urls.static import static
from cliente.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recetas/', include('receta.urls')),
    path('', inicio, name='inicio'),
    path('', include('cliente.urls')),
] 

receta/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name='receta'

urlpatterns = [
    path('ver_recetas', ver_recetas, name='ver_recetas'),
    path('crear_receta', crear_receta, name='crear_receta'),
    path('agregar_ingrediente', agregar_ingrediente, name='agregar_ingrediente'),
    path('quitar_ingrediente', quitar_ingrediente, name='quitar_ingrediente'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/models.py
from django.db import models

cliente/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from gestion_usuarios.forms import *
from .models import *
from django.contrib import messages


#IMPORTANTE: siempre todos los usuarios que se registren perteneceran al grupo "clientes"
#en cada funcion se verifica el grupo al cual pertenece el usuario

# ESTA ES LA VISTA PRINCIPAL DE LA PAGINA, SI EL CLIENTE ESTÁ LOGEADO LO REDIRIGIRA A SU PERFIL
def inicio(request):
    if not request.user.groups.filter(name__in=['clientes']).exists():
        return render(request, 'inicio.html')
    else:
        return redirect('cliente:perfil')

# REGISTRA UN USUARIO MEDIANTE EL METODO POST
def registrar_usuario(request):
    if not request.user.groups.filter(name__in=['clientes']).exists():
        form = Registrarse
        if request.method=='POST':
            form = Registrarse(data=request.POST)
            if form.is_valid():
                user=form.save()
                group=Group.objects.get_or_create(name='clientes')
                group=Group.objects.get(name='clientes')
                user.groups.add(group)
                messages.add_message(request, messages.SUCCESS, "Cliente Registrado Exitosamente. Inicie Sesión", extra_tags='cliente_registrado')
                return redirect('cliente:iniciar_sesion')
            else:
                errores = form.errors
                form = Registrarse
                return render(request, 'cliente/registrarse.html',{'form':form, 'errores':errores})
        return render(request, 'cliente/registrarse.html',{'form':form})
    else:
        if request.user.groups.filter(name__in=['clientes']).exists():
            return redirect('cliente:perfil')

#PERMITE EL INICIO DE SESION DEL CLIENTE Y LO REDIRIGE A SU PERFIL
def iniciar_sesion(request):
    form = Iniciar_sesionform
    if request.method=='POST':
        form = Iniciar_sesionform(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user=authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if request.user.groups.filter(name__in=['clientes']).exists():
                    formpass=CambiarPassForm(request.user)
                    contexto={'formpass':formpass}
                    return render(request, 'cliente/perfil.html', contexto)
                else:
                    logout(request)
                    contexto={'form':form}
                    return render(request, 'cliente/iniciar_sesion.html', contexto)
            else:
                logout(request)
                contexto={'form':form}
                return render(request, 'cliente/iniciar_sesion.html', contexto)
    return render(request, 'cliente/iniciar_sesion.html', {'form':form})

# DIRIGE AL PERFIL DEL CLIENTE, REQUIERE ESTAR LOGEADO PARA PODER ACCEDER, DE LO CONTRARIO SE REDIRIGE A INICIAR SESION
@login_required(login_url='cliente:iniciar_sesion')
def perfil(request):
    if request.user.is_authenticated:
        formpass=CambiarPassForm(request.user)
        if request.user.groups.filter(name__in=['clientes']).exists():
            contexto={'formpass':formpass}
            return render(request, 'cliente/perfil.html', contexto)
        else:
            return redirect('cliente:cerrar_sesion')
    else:
        return redirect('cliente:cerrar_sesion')

# PERMITE EDITAR LOS DATOS DE UN CLIENTE DESDE SU PERFIL, REQUIERE ESTAR LOGEADO
@login_required(login_url='cliente:iniciar_sesion')
def editar_datos(request):
    if request.user.groups.filter(name__in=['clientes']).exists():
        formpass=CambiarPassForm(request.user)
        contexto={'formpass':formpass}
        if request.method=='POST':
            cliente = Usuario.objects.filter(id=request.user.id)
            email=request.POST.get('email')
            first_name=request.POST.get('first_name')
            last_name=request.POST.get('last_name')
            cliente.update(email=email,
                        first_name=first_name,
                        last_name=last_name)
            messages.add_message(request, messages.SUCCESS, "Datos Actualizados Exitosamente", extra_tags='datos_actualizados')
            return redirect('cliente:perfil')
        return render(request, 'cliente/perfil.html', contexto)
    else:
        return redirect('cliente:cerrar_sesion')

# PERMITE CAMBIAR LA CONTRASEÑA DESDE EL PERFIL DEL CLIENTE, REQUIERE ESTAR LOGEADO
@login_required(login_url='cliente:iniciar_sesion')
def cambiar_contrasena(request):
    if request.user.groups.filter(name__in=['clientes']).exists():
        formpass = CambiarPassForm(request.user)
        contexto={'formpass':formpass}
        if request.method=='POST':
            formpass = CambiarPassForm(request.user, request.POST)
            if formpass.is_valid():
                formpass.save()
                formpass = CambiarPassForm(request.user)
                form=Iniciar_sesionform
                contexto={'form':form,
                        'passcambiado':True}
                return render(request, 'cliente/iniciar_sesion.html', contexto)
            else:
                errores_pass=formpass.errors
                formpass = CambiarPassForm(request.user)
                contexto={'formpass':formpass,
                        'errores_pass':errores_pass,
                        'passnocambiado':True
                        }
                return render(request, 'cliente/perfil.html', contexto)
        return redirect('cliente:iniciar_sesion')
    else:
        return redirect('cliente:cerrar_sesion')

# PERMITE TERMINAR O CERRAR LA SESION ACTIVA
@login_required(login_url='cliente:iniciar_sesion')
def cerrar_sesion(request):
    logout(request)
    return redirect('cliente:iniciar_sesion')

templates/cliente/iniciar_sesion.html
{% extends 'base.html' %}


{% block cuerpo %}

{% if passcambiado %}
<div class="alert alert-success text-center" role="alert">
    Contraseña Cambiada Exitosamente. Vuelve a Iniciar Sesión
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

{% if messages %}
        {% for message in messages %}
            {% if 'cliente_registrado' in message.tags %}
                <div class="alert alert-success" role="alert">
                    {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
            {% endif %}
        {% endfor %}
{% endif %}


<br>



<style>
.error{
    color: red;
}
</style>

<div class="container col-lg-5 col-10 redondeado" style="background-color: rgba(19, 19, 19, 0.747); color: white;">
    <h5>Inicio Sesión</h5>
    <hr>
    <form id="inicia_sesion_cliente" action="{% url 'cliente:iniciar_sesion' %}" method="POST">{% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Iniciar Sesión</button>
    </form>
</div>
{% endblock cuerpo %}

templates/cliente/perfil.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'cliente:perfil' %}">Mi Perfil</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'receta:crear_receta' %}">Crear Receta</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'receta:ver_recetas' %}">Ver Recetas</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
            Bienvenido {{user.first_name|upper}} {{user.last_name|upper}}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'cliente:cerrar_sesion' %}">Cerrar Sesión</a>
        </li>
    </ul>
</div>
{% endblock linknav %}

{% block cuerpo %}
    <style>
    .boton{
        text-decoration: none;
        color: white;
    }
    .boton:hover{
        text-decoration: none;
        color: white;
    }
    .error {
    color: #F00;
    }

    .errorDjango{
    color: #F00;
    }
    </style>

    {# APARECERÁ UN MENSAJE DE ERROR SI OCURRE ALGUNO AL CAMBIAR CONTRASENA #}
    {% if passnocambiado %}
    <div class="alert alert-danger" role="alert">
        {% if errores_pass %}
            Error al cambiar contraseña revisa el formulario
        {% endif %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endif %}

    {# AQUI SE VISUALIZAN LOS DATOS DEL PERFIL NOMBRE USUARIO, NOMBRE, APELLIDO, EMAIL #}
    <div class="container mt-5">
        <div class="row">
            <div class="col-4 redondeado" style="background-color: rgba(0, 0, 0, 0.466); color: white;">
                <h4>Mis Datos</h4>
                <form action="" class="mt-4 col-12">
                    <div class="form-group">
                        <label for="">Nombre de Usuario</label>
                        <input type="text" class="form-control" value="{{user.username}}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="">Nombre</label>
                        <input type="text" class="form-control" value="{{user.first_name}}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="">Apellido</label>
                        <input type="text" class="form-control" value="{{user.last_name}}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="text" class="form-control" value="{{user.email}}" readonly>
                    </div>
                </form>
            </div>
            <div class="col-8 text-center">
                <button class="btn btn-warning">
                    <a href="" class="boton" data-toggle="modal" data-target="#modalEditar">Actualizar datos</a>
                </button><br><hr>
                <button class="btn btn-warning">
                    <a href="" class="boton" data-toggle="modal" data-target="#modalContrasena">Cambiar contraseña</a>
                </button>
            </div>
        </div>
    </div>


    <!--MODAL ACTUALIZAR DATOS-->
    <div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Actualizar Datos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="actualizardatos" class="form-group" action="{% url 'cliente:editar_datos' %}" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input class="form-control" type="email" value="{{user.email}}" name="email" id="email" required>
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input class="form-control" type="text" value="{{user.first_name}}" name="first_name" id="nombre" required>
                    </div>
                    <div class="form-group">
                        <label for="apellido">Apellido</label>
                        <input class="form-control" type="text" value="{{user.last_name}}" name="last_name" id="apellido" required>
                    </div>
                    <button type="submit" class="btn btn-success">Actualizar Datos</button>
                </form>
            </div>
            </div>
        </div>
    </div>

    <!--MODAL CAMBIAR CONTRASEÑA-->
    <div class="modal fade" id="modalContrasena" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cambiar Contraseña</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="cambiar_contrasena_cliente" class="form-group" action="{% url 'cliente:cambiar_contrasena' %}" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <label for="">Contraseña Antigua</label>
                        {{formpass.old_password}}
                        <small>
                            {{errores_pass.old_password}}
                        </small>
                    </div>
                    <div class="form-group">
                        <label for="">Contraseña Nueva</label>
                        {{formpass.new_password1}}
                        <small>
                            {{errores_pass.new_password1}}
                        </small>
                    </div>
                    <div class="form-group">
                        <label for="">Contraseña Nueva(Confirmación)</label>
                        {{formpass.new_password2}}
                        <small>
                            {{errores_pass.new_password2}}
                        </small>
                    </div>
                    <button type="submit" class="btn btn-success">Cambiar Contraseña</button>
                </form>
            </div>
            </div>
        </div>
    </div>

{% endblock cuerpo %}

templates/cliente/registrarse.html
{% extends 'base.html' %}
{% load static %}


{% block cuerpo %}

    {# MOSTRARA MENSAJE DE EXITO AL REGISTRARSE #}
    {% if registrarse %}
    <div class="alert alert-success" role="alert">
        Usuario registrado exitosamente
    </div>
    {% endif %}

    <style>
    .error {
    color: #F00;
    }

    .errorDjango{
        color: #F00;
    }
    </style>

    {# FORMULARIO DE REGISTRO DE USUARIO #}
    <div class="container col-lg-5 redondeado" style="background-color: rgba(19, 19, 19, 0.747); color: white;">
        <form id="registrarse" class="form" action="{% url 'cliente:registrar_usuario' %}" method="POST">{% csrf_token %}
            <div class="form-group">
                <label for="username">{{form.username.label}}</label>
                {{form.username}}
                <small class="errorDjango">{{errores.username}}</small>
            </div>
            <div class="form-group">
                <label for="email">{{form.email.label}}</label>
                {{form.email}}
                <small class="errorDjango">{{errores.email}}</small>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <label for="nombre">{{form.first_name.label}}</label>
                    {{form.first_name}}
                </div>
                <div class="form-group col-6">
                    <label for="apellido">Apellido</label>
                    {{form.last_name}}
                </div>
            </div>
            <div class="form-group">
                <label for="">{{form.password1.label}}</label>
                {{form.password1}}
                <small class="errorDjango">{{errores.password1}}</small>
            </div>
            <div class="form-group">
                <label for="password2">{{form.password2.label}}</label>
                {{form.password2}}
                <small class="errorDjango">{{errores.password2}}</small>
            </div>
            <div class="container text-center">
                <button class="btn btn-primary" type="submit">Registrarse</button>
            </div>
        </form>
    </div>
{% endblock cuerpo%}