cliente/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from cliente.views import *

app_name='cliente'

urlpatterns = [
    path('registrar_usuario/', registrar_usuario, name='registrar_usuario'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('editar_datos/', editar_datos, name="editar_datos"),
    path('cambiar_contrasena/', cambiar_contrasena, name="cambiar_contrasena"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpsfood/urls.py
from django.contrib import admin
from django.urls import path, include
from receta.views import *
from gestion_usuarios.views import *
from django.conf import settings
from django.conf.urls.static import static
from cliente.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recetas/', include('receta.urls')),
    path('', inicio, name='inicio'),
    path('', include('cliente.urls')),
] 

receta/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name='receta'

urlpatterns = [
    path('ver_recetas', ver_recetas, name='ver_recetas'),
    path('crear_receta', crear_receta, name='crear_receta'),
    path('agregar_ingrediente', agregar_ingrediente, name='agregar_ingrediente'),
    path('quitar_ingrediente', quitar_ingrediente, name='quitar_ingrediente'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{# load static carga los archivos staticos que ocuparemos en la plantilla base imagenes, js y css #}
{% load static %} 

<!DOCTYPE html>
<html lang="es">
<head>
{% block header %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HELPSFOOD</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    <script src="{% static 'js/validaciones.js' %}"></script>
{% endblock header %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'inicio' %}" style="color: GREEN;"> <u>HELPSFOOD</u></a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        {# En este bloque: linknav se pueden modificar los links de la barra de navegacion #}
        {% block linknav %}
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'cliente:perfil' %}">Mi Perfil</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'receta:crear_receta' %}">Crear Receta</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'receta:ver_recetas' %}">Ver Recetas</a>
                  </li>
              </ul>
              <ul class="navbar-nav ml-auto">
                      Bienvenido {{user.first_name|upper}} {{user.last_name|upper}}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'cliente:cerrar_sesion' %}">Cerrar Sesión</a>
                  </li>
              </ul>
          </div>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'receta:ver_recetas' %}">Ver Recetas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'receta:crear_receta' %}">Crear Receta</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cliente:registrar_usuario' %}">Registrarse</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cliente:iniciar_sesion' %}">Iniciar Sesión</a>
              </li>
            </ul>
          </div>
          {% endif %}
        
        {% endblock linknav %}
      </nav>

      {# En este block cuerpo podemos agregar todo el codigo que necesitamos para el body #}
      {% block cuerpo %}
      {% endblock cuerpo %}

</body>
</html>

templates/inicio.html
{% extends 'base.html' %}

{% block cuerpo %}
    <style>
        .botoninicio{
            text-decoration: none;
            color: white;
            display: inline-block;
        }
        .botoninicio:hover{
            text-decoration: none;
            color: white;
        }
    </style>

    <br>
    <div class="container redondeado" style="background-color: rgba(19, 19, 19, 0.815); color: white;">
        <br>
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="col-12 text-center">
                    <h4>Bienvenido a <strong>HELPSFOOD</strong></h4>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum<hr>
                <button class="btn btn-primary">
                    <a href="{% url 'cliente:iniciar_sesion' %}" class="botoninicio">Iniciar Sesión</a>
                </button><br>
                <small><a href="{% url 'cliente:registrar_usuario' %}">¿No tienes cuenta? Registrate</a></small>
                </div>
            </div>
        </div>
        <br>
    </div>
{% endblock cuerpo %}